site_name: glaucus Wiki
nav:
  - Home: index.md
  - Preface:
    - i. Foreword: preface/foreword.md
    - ii. Audience: preface/audience.md
    - iii. glaucus Target Architectures: preface/glaucus-target-architectures.md
    - iv. glaucus and Standards: preface/glaucus-and-standards.md
    - v. Rationale for Cerata: preface/rationale-for-cerata.md
    - vi. Prerequisites: preface/prerequisites.md
    - vii. Typography: preface/typography.md
    - viii. Structure: preface/structure.md
    - ix. Errata: preface/errata.md
  - I. Introduction:
    - 1. Introduction:
      - 1.1. How to Build glaucus: introduction/introduction/how-to-build-glaucus.md
      - 1.2. Resources: introduction/introduction/resources.md
      - 1.3. Help: introduction/introduction/help.md
  - II. Constructing the Toolchain and the Chroot Environment:
    - 2. Preparing the Host System:
      - 2.1. Introduction: constructing-the-toolchain-and-the-chroot-environment/preparing-the-host-system/introduction.md
      - 2.2. Host System Requirements: constructing-the-toolchain-and-the-chroot-environment/preparing-the-host-system/host-system-requirements.md
      - 2.3. Building glaucus in Stages: constructing-the-toolchain-and-the-chroot-environment/preparing-the-host-system/building-glaucus-in-stages.md
    - 3. Cerata and Patches:
      - 3.1. Introduction: constructing-the-toolchain-and-the-chroot-environment/cerata-and-patches/introduction.md
      - 3.2. All Cerata: constructing-the-toolchain-and-the-chroot-environment/cerata-and-patches/all-cerata.md
      - 3.3. Needed Patches: constructing-the-toolchain-and-the-chroot-environment/cerata-and-patches/needed-patches.md
    - 4. Final Preparations:
      - 4.1. Introduction: constructing-the-toolchain-and-the-chroot-environment/final-preparations/introduction.md
      - 4.2. Adding the glaucus User and Group: constructing-the-toolchain-and-the-chroot-environment/final-preparations/adding-the-glaucus-user-and-group.md
      - 4.3. Cloning the glaucus Repository: constructing-the-toolchain-and-the-chroot-environment/final-preparations/cloning-the-glaucus-repository.md
      - 4.4. Initializing the glaucus Repository: constructing-the-toolchain-and-the-chroot-environment/final-preparations/initializing-the-glaucus-repository.md
      - 4.5. Setting Up the Environment: constructing-the-toolchain-and-the-chroot-environment/final-preparations/setting-up-the-environment.md
      - 4.6. About CCUs and CEUs: constructing-the-toolchain-and-the-chroot-environment/final-preparations/about-ccus-and-ceus.md
      - 4.7. About the Test Suites: constructing-the-toolchain-and-the-chroot-environment/final-preparations/about-the-test-suites.md
    - 5. Constructing the Toolchain:
      - 5.1. Introduction: constructing-the-toolchain-and-the-chroot-environment/constructing-the-toolchain/introduction.md
      - 5.2. Toolchain Technical Notes: constructing-the-toolchain-and-the-chroot-environment/constructing-the-toolchain/toolchain-technical-notes.md
      - 5.3. General Compilation Instructions: constructing-the-toolchain-and-the-chroot-environment/constructing-the-toolchain/general-compilation-instructions.md
    - 6. Constructing the Chroot Environment:
      - 6.1. Introduction: constructing-the-toolchain-and-the-chroot-environment/constructing-the-chroot-environment/introduction.md
      - 6.2. Stripping: constructing-the-toolchain-and-the-chroot-environment/constructing-the-chroot-environment/stripping.md
      - 6.3. Changing Ownership: constructing-the-toolchain-and-the-chroot-environment/constructing-the-chroot-environment/changing-ownership.md
  - III. Constructing and Envenomating glaucus:
    - 7. Installing Basic System Cerata:
      - 7.1. Introduction: constructing-and-envenomating-glaucus/installing-basic-system-cerata/introduction.md
      - 7.2. Preparing Virtual Kernel File Systems: constructing-and-envenomating-glaucus/installing-basic-system-cerata/preparing-virtual-kernel-file-systems.md
      - 7.3. Package Management: constructing-and-envenomating-glaucus/installing-basic-system-cerata/package-management.md
      - 7.4. Entering the Chroot Environment: constructing-and-envenomating-glaucus/installing-basic-system-cerata/entering-the-chroot-environment.md
      - 7.5. Creating Directories: constructing-and-envenomating-glaucus/installing-basic-system-cerata/creating-directories.md
      - 7.6. Creating Essential Files and Symlinks: constructing-and-envenomating-glaucus/installing-basic-system-cerata/creating-essential-files-and-symlinks.md
      - 7.8. Adjusting the Toolchain: constructing-and-envenomating-glaucus/installing-basic-system-cerata/adjusting-the-toolchain.md
      - 7.10. About Debugging Symbols: constructing-and-envenomating-glaucus/installing-basic-system-cerata/about-debugging-symbols.md
      - 7.11. Stripping Again: constructing-and-envenomating-glaucus/installing-basic-system-cerata/stripping-again.md
      - 7.12. Cleaning Up: constructing-and-envenomating-glaucus/installing-basic-system-cerata/cleaning-up.md
    - 8. System Configuration:
      - 8.1. Introduction: constructing-and-envenomating-glaucus/system-configuration/introduction.md
      - 8.2. Overview of Device and Module Handling: constructing-and-envenomating-glaucus/system-configuration/overview-of-device-and-module-handling.md
      - 8.3. Managing Devices: constructing-and-envenomating-glaucus/system-configuration/managing-devices.md
      - 8.4. General Network Configuration: constructing-and-envenomating-glaucus/system-configuration/general-network-configuration.md
      - 8.5. s6 Boot Scripts Usage and Configuration: constructing-and-envenomating-glaucus/system-configuration/s6-boot-scripts-usage-and-configuration.md
      - 8.6. OKSH Startup Files: constructing-and-envenomating-glaucus/system-configuration/oksh-startup-files.md
      - 8.8. Creating the /etc/shells File: constructing-and-envenomating-glaucus/system-configuration/creating-the-etc-shells-file.md
    - 9. Making glaucus Bootable:
      - 9.1. Introduction: constructing-and-envenomating-glaucus/making-glaucus-bootable/introduction.md
      - 9.2. Creating the /etc/fstab File: constructing-and-envenomating-glaucus/making-glaucus-bootable/creating-the-etc-fstab-file.md
    - 10. The End:
      - 10.1. The End: constructing-and-envenomating-glaucus/the-end/the-end.md
      - 10.2. Get Counted: constructing-and-envenomating-glaucus/the-end/get-counted.md
      - 10.3. Rebooting the System: constructing-and-envenomating-glaucus/the-end/rebooting-the-system.md
      - 10.4. What Now?: constructing-and-envenomating-glaucus/the-end/what-now.md
  - IV. Appendices:
    - A. Acronyms and Terms: appendices/acronyms-and-terms.md
    - B. Acknowledgements: appendices/acknowledgements.md
    - C. Cysts: appendices/cysts.md
    - D. s6 Boot Scripts: appendices/s6-boot-scripts.md
    - E. glaucus Licenses:
      - E.1. The ISC License: appendices/glaucus-licenses/the-isc-license.md
site_url: https://wiki.glaucuslinux.org/
site_description: glaucus Wiki
site_author: Firas Khalil Khana
theme:
  name: material
  custom_dir: custom
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  favicon: 'img/favicon.png'
  logo: 'img/logo.svg'
  palette:
    primary: Blue Grey
    accent: Amber
copyright: "<p>Copyright © 2019-2020, <a href='mailto:firasuke@glaucuslinux.org'>Firas Khalil Khana</a></p>
<p>Distributed under the terms of the <a href='https://github.com/glaucuslinux/glaucus/blob/master/LICENSE'>ISC</a> License</p>
<p>Linux® is the registered trademark of Linus Torvalds in the U.S. and other countries.</p>"
repo_url: https://github.com/glaucuslinux/glaucus
repo_name: glaucuslinux/glaucus
edit_uri: ''
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
strict: true
remote_branch: 'master'
plugins:
  - search
  - minify:
      minify_html: true
